# Site Settings
title: Mu Cyber
email: mucyberlab@gmail.com
description: A group of people that learn cybersecurity together.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mucyber.org" # the base hostname & protocol for your site
google_analytics: "UA-111260853-1"

# User Settings
username: Mu Cyber
user_description: A group of people that learn cybersecurity together.
disqus_username: MuCyberLab

# Social Media
# Remove the item if you don't need it
github_username: MuCyberLab
facebook_username: MuCyberLab
twitter_username: MuCyberLab

# Build settings
markdown: kramdown
highlighter: rouge
permalink: blog/:title-D:year:month:day.html

# Plugins
gems:
  - jemoji
  - jekyll-redirect-from

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Ä°HE
    url: /ihe/
  - title: CTF
    url: https://ctf.mucyber.org
  - title: Contact
    url: /contact/

# Exclude my node related stuff
include: ["_pages"]
exclude: ['package.json', 'src', 'node_modules','README.md','LICENSE']
